version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: socialpost
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    command: celery -A frontend.app.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
volumes:
  postgres_data: