import {ArrowRight, Check, ChevronsUpDown, Circle, Copy, Edit, ExternalLink, File, HelpCircle, Home, Loader2, LogOut, Mail, MessageSquare, Moon, Plus, PlusCircle, Search, Server, Settings, Share2, Shield, Sun, Trash, User, X, Workflow} from 'lucide-react';
import { FaFacebook, FaLinkedin, FaTwitter, FaInstagram, FaGoogle } from 'react-icons/fa';

const Icons = {
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  google: FaGoogle,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  logout: LogOut,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User,
  linkedin: FaLinkedin,
  facebook: FaFacebook,
  twitter: FaTwitter,
  instagram: FaInstagram,
};

export {Icons};
